name = "erdos307_prime_factors"
version = "0.1.0"
defaultTargets = ["Erdos307"]

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "0df444a360eaa60ab8c11dca51a86af692955474"

[[lean_lib]]
name = "Erdos307"
